name: Github Actions Example

on:
  push:
    branches:
      - main   
job:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
        - name: Echo Message
          run: |
            echo "Hello Brayan"
            